### ISSUE TITLE
App crashes on joining meeting 

### ISSUE THREAD

**Issue by roopaish** [craigspicer/flutter_zoom_sdk#1]
I am using the newest Flutter SDK `Flutter 3.10.1 • channel stable`.
Can you please verify if it works on the new flutter SDK?

So I had to change the buildscript a little bit 
```gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.1' <--- here
    }
}
```

I am using android 13 real device.

<summary>
Logs while crashing

<details>

  E/FileUtils(30101): err write to mi_exception_log
  D/CompatibilityChangeReporter(30101): Compat change id reported: 160794467; UID 10899; state: ENABLED
  D/OpenGLRenderer(30101): --- Failed to create image decoder with message 'unimplemented'
  D/DecorView[](30101): onWindowFocusChanged hasWindowFocus false
  D/MiuiMultiWindowAdapter(30101): MiuiMultiWindowAdapter::getFreeformVideoWhiteListInSystem::LIST_ABOUT_SUPPORT_LANDSCAPE_VIDEO = [com.hunantv.imgo.activity, com.tencent.qqlive, com.qiyi.video, com.hunantv.imgo.activity.inter, com.tencent.qqlivei18n, com.iqiyi.i18n, tv.danmaku.bili]
  D/IS_CTS_MODE(30101): true
  D/MULTI_WINDOW_ENABLED(30101): false
  D/DecorView[](30101): getWindowModeFromSystem  windowmode is 1
  D/CompatibilityChangeReporter(30101): Compat change id reported: 171228096; UID 10899; state: ENABLED
  D/CompatibilityChangeReporter(30101): Compat change id reported: 210923482; UID 10899; state: ENABLED
  D/AndroidRuntime(30101): Shutting down VM
  E/AndroidRuntime(30101): FATAL EXCEPTION: main
  E/AndroidRuntime(30101): Process: com.evilratt.flutter_zoom_sdk_example, PID: 30101
  E/AndroidRuntime(30101): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ViewModelKt;
  E/AndroidRuntime(30101): 	at us.zoom.feature.pbo.ui.ZmPBOViewModel.<init>(ZmPBOViewModel.kt:33)
  E/AndroidRuntime(30101): 	at us.zoom.feature.pbo.ui.ZmPBOViewModel$b.create(ZmPBOViewModel.kt:1)
  E/AndroidRuntime(30101): 	at us.zoom.feature.pbo.ui.ZmPBOUI.c(ZmPBOUI.kt:2)
  E/AndroidRuntime(30101): 	at us.zoom.feature.pbo.ui.ZmPBOUI.a(ZmPBOUI.kt:12)
  E/AndroidRuntime(30101): 	at us.zoom.feature.pbo.ZmPBOServiceImpl.initialize(ZmPBOServiceImpl.kt:3)
  E/AndroidRuntime(30101): 	at us.zoom.proguard.y03.a(ZmPBOHelper.java:6)
  E/AndroidRuntime(30101): 	at com.zipow.videobox.conference.ui.ZmFoldableConfActivity.initData(ZmFoldableConfActivity.java:8)
  E/AndroidRuntime(30101): 	at com.zipow.videobox.conference.ui.ZmFoldableConfActivity.onCreate(ZmFoldableConfActivity.java:14)
  E/AndroidRuntime(30101): 	at android.app.Activity.performCreate(Activity.java:8523)
  E/AndroidRuntime(30101): 	at android.app.Activity.performCreate(Activity.java:8487)
  E/AndroidRuntime(30101): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438)
  E/AndroidRuntime(30101): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
  E/AndroidRuntime(30101): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980)  
E/AndroidRuntime(30101): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(30101): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(30101): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(30101): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
E/AndroidRuntime(30101): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(30101): 	at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime(30101): 	at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime(30101): 	at android.app.ActivityThread.main(ActivityThread.java:8296)
E/AndroidRuntime(30101): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30101): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/AndroidRuntime(30101): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
E/AndroidRuntime(30101): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ViewModelKt" on path: DexPathList[[zip file "/data/app/~~-FAGqridOumCPSY4tPflAw==/com.evilratt.flutter_zoom_sdk_example-X0y2WAfTGAbe5RQkz4ZwNQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~-FAGqridOumCPSY4tPflAw==/com.evilratt.flutter_zoom_sdk_example-X0y2WAfTGAbe5RQkz4ZwNQ==/lib/arm64, /data/app/~~-FAGqridOumCPSY4tPflAw==/com.evilratt.flutter_zoom_sdk_example-X0y2WAfTGAbe5RQkz4ZwNQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(30101): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(30101): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(30101): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(30101): 	... 24 more
W/oom_sdk_example(30101): type=1400 audit(0.0:720945): avc: denied { search } for name="miuilog" dev="dm-41" ino=1062778 scontext=u:r:untrusted_app:s0:c131,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.android.chrome
W/oom_sdk_example(30101): type=1400 audit(0.0:720946): avc: denied { search } for name="miuilog" dev="dm-41" ino=1062778 scontext=u:r:untrusted_app:s0:c131,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.android.chrome
W/oom_sdk_example(30101): type=1400 audit(0.0:720947): avc: denied { search } for name="miuilog" dev="dm-41" ino=1062778 scontext=u:r:untrusted_app:s0:c131,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.android.chrome
W/OOMEventManagerFK(30101): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
W/oom_sdk_example(30101): type=1400 audit(0.0:720949): avc: denied { search } for name="miuilog" dev="dm-41" ino=1062778 scontext=u:r:untrusted_app:s0:c131,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.android.chrome
W/oom_sdk_example(30101): type=1400 audit(0.0:720950): avc: denied { search } for name="miuilog" dev="dm-41" ino=1062778 scontext=u:r:untrusted_app:s0:c131,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.android.chrome
W/oom_sdk_example(30101): type=1400 audit(0.0:720951): avc: denied { getattr } for path="/data/miuilog" dev="dm-41" ino=1062778 scontext=u:r:untrusted_app:s0:c131,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.android.chrome
W/oom_sdk_example(30101): type=1400 audit(0.0:720952): avc: denied { search } for name="miuilog" dev="dm-41" ino=1062778 scontext=u:r:untrusted_app:s0:c131,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.android.chrome
W/oom_sdk_example(30101): type=1400 audit(0.0:720953): avc: denied { search } for name="miuilog" dev="dm-41" ino=1062778 scontext=u:r:untrusted_app:s0:c131,c259,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.android.chrome
E/FileUtils(30101): err write to mi_exception_log
I/Process (30101): Process is going to kill itself!
I/Process (30101): java.lang.Exception
I/Process (30101): 	at android.os.Process.killProcess(Process.java:1344)
I/Process (30101): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
I/Process (30101): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
I/Process (30101): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
I/Process (30101): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
I/Process (30101): Sending signal. PID: 30101 SIG: 9
Lost connection to device.
Exited (sigterm)
</details>
</summary>

Also there were some of these errors: ` Access denied finding property "vendor.camera.aux.packagelist"`

**Comment by ananthu-evm** [comment]
Getting the same error! @craigspicer any update?
<img width="1171" alt="Screenshot 2023-05-23 at 12 50 22 PM" src="https://github.com/craigspicer/flutter_zoom_sdk/assets/92381725/89b88098-56a8-4cc7-b467-ebd22601396e">

**Comment by craigspicer** [comment]
I will have to try on the latest Flutter version when I have some time. I updated the Zoom SDKs to the very latest for both Android and iOS (5.14.5) in my last commit. I'm currently running Flutter 3.7.8.

**Comment by ananthu-evm** [comment]
@craigspicer 
I got the same issue on Flutter 3.0.0.

**Comment by craigspicer** [comment]
What device are you using to test with?

**Comment by ananthu-evm** [comment]
Android 12 real device.

**Comment by craigspicer** [comment]
This crash seems to indicate a missing androidx.lifecycle library. Try adding these dependencies to your app level build.gradle file:

dependencies {
    def lifecycle_version = "2.4.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.android.exoplayer:exoplayer:2.17.1'
}

**Comment by ananthu-evm** [comment]
@craigspicer I added the above code, but still getting the same!

<img width="1163" alt="Screenshot 2023-05-23 at 2 17 27 PM" src="https://github.com/craigspicer/flutter_zoom_sdk/assets/92381725/b05851c4-6048-4ddb-8315-178210a56b85">

**Comment by craigspicer** [comment]
I'm not able to reproduce this with an Android 12 real device. Try to delete everything to do with flutter_zoom_sdk in your .pub-cache/git folder.

Then remove the dependency, run pub get, add the dependency back, run pub get and then run the command
flutter_zoom_sdk:unzip_zoom_sdk

**Comment by ananthu-evm** [comment]
@craigspicer All things are done but still, the application getting crashed. why?

**Comment by craigspicer** [comment]
Try adding this to your app level build.gradle file:

    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'

In your project level build.gradle file, use this kotlin version:

buildscript {
    ext.kotlin_version = '1.8.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
    }
}

Compile and run in release mode.

**Comment by edmirmob** [comment]
> @craigspicer All things are done but still, the application getting crashed. why?

Did you resolve issue?
I got the same.

**Comment by edmirmob** [comment]
> Try adding this to your app level build.gradle file:
> 
> ```
> implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
> implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
> ```
> 
> In your project level build.gradle file, use this kotlin version:
> 
> buildscript { ext.kotlin_version = '1.8.0' repositories { google() mavenCentral() }
> 
> ```
> dependencies {
>     classpath 'com.android.tools.build:gradle:7.2.1'
>     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>     classpath 'com.google.gms:google-services:4.3.13'
>     classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
> }
> ```
> 
> }
> 
> Compile and run in release mode.

after I added the code above I still have the same error
